trigger:
  - none

resources:
- repo: self

variables:
  branch: '$(Build.SourceBranchName)'
  buildNumber: '$(Build.BuildNumber)'

stages:
- stage: BuildAndPush
  displayName: Build docker image and push to ACR
  jobs:
  - job: BuildAndPush
    displayName: Build docker image and push to ACR
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - script: |
        echo $sourceVersion
        commitHash=${sourceVersion:0:8}
        echo $commitHash
        echo "##vso[task.setvariable variable=commitHash]$commitHash" ## Set variable for using in other tasks.
      env: { sourceVersion: $(Build.SourceVersion) }
      displayName: Git Hash 8-digit
      workingDirectory: $(Build.SourcesDirectory)
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        containerRegistry: 'MKTFEACR'
        repository: 'nginx-ip2l'
        dockerfile: 'Dockerfile-ip2l'
        tags: |
          $(branch).$(commitHash).$(buildNumber)
