trigger:
- none

resources:
  pipelines:
    - pipeline: htmltrigger
      source: 'aks-html-test' #因為不支持在下面的github repository直接配置trigger，所以要用另外一個pipeline去觸發
      trigger:
        branches: 
        - master
  repositories:
  - repository: htmlsrc # The name used to reference this repository in the checkout step
    type: github
    endpoint: cjh829
    name: cjh829/aks-html-test
    ref: master

variables:
  # Container registry service connection established during pipeline creation
  AzureCR: 'myacr'
  containerRegistry: 'cjh829.azurecr.io'
  imageRepository: 'aks-nginx-test'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.SourceVersion)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - checkout: htmlsrc
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(AzureCR)
        tags: |
          $(tag)
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s'
        artifact: 'manifests'
        publishLocation: 'pipeline'