trigger:
- none

resources:
  pipelines:
    - pipeline: htmltrigger
      source: 'cjh829.aks-html-test' #因為不支持在下面的github repository直接配置trigger，所以要用另外一個pipeline去觸發
      trigger:
        branches: 
        - master
  repositories:
  - repository: htmlsrc # The name used to reference this repository in the checkout step
    type: github
    endpoint: cjh829
    name: cjh829/aks-html-test
    ref: master

variables:
  tag: '$(Build.SourceVersion)'

pool:
  vmImage: 'ubuntu-latest'
steps:
- checkout: self
- checkout: htmlsrc
- task: CopyFiles@2
  inputs:
    SourceFolder: 'aks-html-test'
    Contents: '**'
    TargetFolder: 'aks-nginx-test/nginx/html'
    CleanTargetFolder: true

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    containerRegistry: 'myacr'
    repository: 'aks-nginx-test'
    dockerfile: 'aks-nginx-test/Dockerfile'
    tags: |
      $(tag)
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'aks-nginx-test/k8s.yml'
    artifact: 'manifests'
    publishLocation: 'pipeline'