# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  imagePullSecret: 'aksnginxtestk8ssecret'

pool:
  vmImage: 'ubuntu-latest'
  environment: $(branch)

steps:
# no need to checkout, just one yaml so we download it directly.
- checkout: none
- task: CmdLine@2
  displayName: 'download k8s yaml directly'
  inputs:
    script: 'wget https://raw.githubusercontent.com/cjh829/aks-nginx-test/master/k8s-master.yaml'
- task: KubernetesManifest@0
  displayName: Create imagePullSecret
  inputs:
    action: createSecret
    kubernetesServiceConnection: 'myk8s'
    namespace: 'default'
    secretType: 'dockerRegistry'
    secretName: $(imagePullSecret)
    dockerRegistryEndpoint: 'myacr'

- task: KubernetesManifest@0
  displayName: Deploy to Kubernetes cluster
  inputs:
    action: deploy
    kubernetesServiceConnection: 'myk8s'
    namespace: 'default'
    manifests: |
      k8s-master.yaml
    imagePullSecrets: |
      $(imagePullSecret)
    #note the containers should be full url(cjh829.azurecr.io), can not replace to 'myacr' which will not replace the image source in k8s.yaml
    containers: |
      cjh829.azurecr.io/aks-nginx-test:$(branch).$(commitHash).$(buildNumber)