trigger:
- none

resources:
- repo: self

variables:
  branch: '$(Build.SourceBranchName)'
  buildNumber: '$(Build.BuildNumber)'
  imageRepository: 'aks-nginx-ip2l'
  imagePullSecret: 'aksnginxip2lk8ssecret'

stages:
- stage: PackAndPush
  displayName: Pack website to docker image and push to ACR
  jobs:
  - job: PackAndPush
    displayName: Pack website to docker image and push to ACR
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        containerRegistry: 'myacr'
        repository: $(imageRepository)
        dockerfile: 'Dockerfile-ip2l'
        tags: |
          $(branch).$(buildNumber)
    - task: KubernetesManifest@0
      displayName: Create imagePullSecret
      inputs:
        action: createSecret
        kubernetesServiceConnection: 'myk8s'
        namespace: 'default'
        secretType: 'dockerRegistry'
        secretName: $(imagePullSecret)
        dockerRegistryEndpoint: 'myacr'

    - task: KubernetesManifest@0
      displayName: Deploy to Kubernetes cluster
      inputs:
        action: deploy
        kubernetesServiceConnection: 'myk8s'
        namespace: 'default'
        manifests: |
          k8s-ip2l.yaml
        imagePullSecrets: |
          $(imagePullSecret)
        #note the containers should be full url(cjh829.azurecr.io), can not replace to 'myacr' which will not replace the image source in k8s-ip2l.yaml
        containers: |
          cjh829.azurecr.io/$(imageRepository):$(branch).$(buildNumber)
