FROM mktfeacr.azurecr.io/nginx-ip2l:base
COPY nginx/conf.d/default-ip2l.conf /etc/nginx/conf.d/default.conf
COPY nginx/fastcgi.conf /etc/nginx/fastcgi.conf
COPY nginx/fastcgi_params /etc/nginx/fastcgi_params
COPY nginx/mime.types /etc/nginx/mime.types
COPY nginx/nginx-ip2l.conf /etc/nginx/nginx.conf
COPY nginx/DB1.BIN /etc/ip2location/DB1.BIN
ADD nginx/html /usr/share/nginx/html
RUN chmod +r /usr/share/nginx/html
