version: '3'

services:
  nginx:
    image: aks-nginx-test-ip2l:test
    volumes:
      - ./nginx/conf.d/default-ip2l.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/nginx-ip2l.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    ports:
      - "80:80"
    container_name: aks-nginx-test-ip2l
