version: '3'

services:
  nginx:
    image: aks-nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "80:80"
    container_name: aks-nginx-test