apiVersion: v1
kind: Service
metadata:
  name: nginx-service-ip2l
  labels:
    app: nginx
    env: test
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local #get client's real ip
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: nginx
    env: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-ip2l
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      env: test
  template:
    metadata:
      labels:
        app: nginx
        env: test
    spec:
      containers:
        - name: nginx-container-ip2l
          image: cjh829.azurecr.io/aks-nginx-ip2l
          lifecycle:
            preStop:
              exec:
                # nginx -s quit gracefully terminate while SIGTERM triggers a quick exit
                command: [ "/usr/sbin/nginx","-s","quit" ]
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
