#shared persistentVolume for all env(master and instanceN) && all lang/mobile
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: az-file-premium
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
parameters:
  skuName: Premium_LRS
mountOptions:
  - mfsymlinks
  - actimeo=30
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-file-premium-pvc-f1dev-master
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: az-file-premium
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-file-premium-pvc-f1dev-instacne-01
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: az-file-premium
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-file-premium-pvc-f1dev-instacne-02
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: az-file-premium
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-file-premium-pvc-f1dev-instacne-03
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: az-file-premium
  resources:
    requests:
      storage: 10Gi
