apiVersion: v1
kind: Service
metadata:
  name: nginx-service-instance-01
  labels:
    app: nginx
    env: instance-01
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local #get client's real ip
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
    env: instance-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-instance-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      env: instance-01
  template:
    metadata:
      labels:
        app: nginx
        env: instance-01
    spec:
      containers:
      - name: nginx-container-instance-01
        image: cjh829.azurecr.io/aks-nginx-test
        lifecycle:
          preStop:
            exec:
            # sleep then graceful shutdown
            command: [
                "sh", "-c", "sleep 15 && /usr/sbin/nginx -s quit",
            ]
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
