apiVersion: v1
kind: Service
metadata:
  name: nginx-service-master
  labels:
    app: nginx
    env: master
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
    env: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      env: master
  template:
    metadata:
      labels:
        app: nginx
        env: master
    spec:
      containers:
      - name: nginx-container-master
        image: cjh829.azurecr.io/aks-nginx-test
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
