apiVersion: v1
kind: Service
metadata:
  name: nginx-service-f1-dev-master
  labels:
    app: nginx
    prod: f1
    env: dev
    branch: master
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
    prod: f1
    env: dev
    branch: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-f1-dev-master
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      prod: f1
      env: dev
      branch: master
  template:
    metadata:
      labels:
        app: nginx
        prod: f1
        env: dev
        branch: master
    spec:
      containers:
      - name: nginx-container-f1-dev-master
        image: mktfeacr.azurecr.io/nginx-ip2l
        lifecycle:
          preStop:
            exec:
              # sleep then graceful shutdown
              command: [
                  "sh", "-c", "sleep 15 && /usr/sbin/nginx -s quit",
              ]
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: pvc
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: az-file-premium-pvc-f1-dev-master
